# Default values for shipa.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

auth:
  dummyDomain: "@shipa.io"

shipaApi:
  port: 8080
  image: shipasoftware/api:helm-v1.0.68
  pullPolicy: Always
  debug: false

license: ""

service:
  traefik:
    httpPort: 80
    httpsPort: 443
    enable: true
    rbac: true
    debug: false
#    serviceType: ClusterIP
    serviceType: LoadBalancer
#    clusterIP: 10.100.10.11
#    loadBalancerIP: 104.154.157.13
  nginx:
    enabled: true
    serviceType: LoadBalancer
#    serviceType: ClusterIP
    #clusterIP: 10.100.10.10
#    loadBalancerIP: 35.202.88.71

dashboard:
  enabled: true
  image: shipasoftware/dashboard:v2.0.14

etcd:
  debug: false
  #password: bingo
  persistence:
    accessMode: 'ReadWriteOnce'
    size: 10Gi

postgres:
  persistence:
    accessMode: 'ReadWriteOnce'
    size: 10Gi

guardian:
  sshPort: 22
  image: shipasoftware/guardian:helm-chart
  pullPolicy: Always
  persistence:
    homeGit:
      accessMode: 'ReadWriteOnce'
      size: 10Gi
    repositories:
      accessMode: 'ReadWriteOnce'
      size: 10Gi

cli:
  image: shipasoftware/cli:v0.0.68
  pullPolicy: Always

metrics:
  image: shipasoftware/metrics:v0.0.5
  pullPolicy: Always

  # Extra configuration to add to prometheus.yaml
  # extraPrometheusConfiguration: |
  #   remote_read:
  #      - url: http://localhost:9268/read
  #   remote_write:
  #      - url: http://localhost:9268/write
  extraPrometheusConfiguration:
  #password: hardcoded

busybody:
  image: shipasoftware/bb:v0.0.2

netdata:
  image: shipasoftware/netdata:v0.0.3

shipaNodeTraefik:
  image: shipasoftware/shipa-node-traefik:v0.0.1
  user: admin

platforms:
  - static

# --------------------------------------------------------------------------

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

rbac:
  enabled: true


mongodb-replicaset:
  replicaSetName: rs0
  replicas: 1
  port: 27017
  auth:
    enabled: false
  installImage:
    name: k8s.gcr.io/mongodb-install
    tag: 0.6
    pullPolicy: IfNotPresent
  image:
    name: mongo
    tag: latest
    pullPolicy: IfNotPresent
  persistentVolume:
    enabled: true
    size: 10Gi
  tls:
    enabled: false
  configmap:


docker-registry:
  persistence:
    accessMode: 'ReadWriteOnce'
    enabled: true
    size: 10Gi
  service:
    port: 5000
  tlsSecretName: shipa-certificates
  configData:
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
    http:
      # Don't change 5000 here
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
    auth:
      token:
        # We inject realm as env variable
        service: shipa-registry
        issuer: shipa-token-issuer
        rootcertbundle: /etc/ssl/docker/ca.pem
