apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  type: ClusterIP
  clusterIP: 10.100.10.101
  ports:
    - name: mongodb
      port: 27017
  selector:
    app: mongodb-replicaset
    release: shipa

