apiVersion: v1
kind: Secret
metadata:
  name: shipa-certificates
  labels:
    app: {{ template "shipa.name" . }}
    chart: {{ template "shipa.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  ca.pem: ""
  ca-key.pem: ""
  cert.pem: ""
  key.pem: ""
  tls.crt: ""
  tls.key: ""
