apiVersion: v1
kind: Secret
metadata:
  name: shipa-certificates
  labels: {{- include "shipa.labels" . | nindent 4 }}
data:
  ca.pem: ""
  ca-key.pem: ""
  cert.pem: ""
  key.pem: ""
  tls.crt: ""
  tls.key: ""
