apiVersion: v1
kind: Service
metadata:
  name: {{ include "shipa.fullname" . }}-clair
  labels:
    name: {{ include "shipa.fullname" . }}-clair
spec:
  type: ClusterIP
  ports:
    - port: 6060
      targetPort: 6060
      protocol: TCP
      name: clair
    - port: 6061
      targetPort: 6061
      protocol: TCP
      name: health
  selector:
    name: {{ include "shipa.fullname" . }}-clair
