apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "shipa.fullname" . }}-clair
  labels: {{- include "shipa.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      name: {{ template "shipa.fullname" . }}-clair
  template:
    metadata:
      labels:
        name: {{ template "shipa.fullname" . }}-clair
    spec:
      containers:
        - name: clair
          image: gcr.io/shipa-1000/clair:v2.0.9
          args:
            - --insecure-tls=true
          imagePullPolicy: Always
          ports:
            - name: clair
              containerPort: 6060
              protocol: TCP
            - name: health
              containerPort: 6061
              protocol: TCP
          volumeMounts:
            - name: {{ template "shipa.fullname" . }}-clair-config
              mountPath: /clair-config/
            - name: config-dir
              mountPath: /etc/clair/
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "shipa.fullname" . }}-secret
                  key: postgres-password
      volumes:
        - name: config-dir
          emptyDir: {}
        - name: {{ template "shipa.fullname" . }}-clair-config
          configMap:
            name: {{ template "shipa.fullname" . }}-clair-config
            items:
              - key: config.template.yaml
                path: config.template.yaml
