apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "shipa.fullname" . }}-clair
  labels: {{- include "shipa.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      name: {{ template "shipa.fullname" . }}-clair
  template:
    metadata:
      labels:
        name: {{ template "shipa.fullname" . }}-clair
    spec:
      containers:
        - name: clair
          image: quay.io/coreos/clair:v2.0.9
          args:
            - --insecure-tls=true
          imagePullPolicy: IfNotPresent
          ports:
            - name: clair
              containerPort: 6060
              protocol: TCP
            - name: health
              containerPort: 6061
              protocol: TCP
          volumeMounts:
            - name: {{ template "shipa.fullname" . }}-clair-config
              mountPath: /etc/clair/
      volumes:
        - name: {{ template "shipa.fullname" . }}-clair-config
          configMap:
            name: {{ template "shipa.fullname" . }}-clair-config
            items:
                - key: config.yaml
                  path: config.yaml
