apiVersion: v1
kind: Service
metadata:
  name: {{ include "shipa.fullname" . }}-etcd
  labels:
    name: etcd
spec:
  type: ClusterIP
  ports:
    - port: 2379
      targetPort: http
      protocol: TCP
      name: http
  selector:
    name: etcd
