apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shipa.fullname" . }}-etcd
  labels: {{- include "shipa.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      name: {{ include "shipa.fullname" . }}-etcd
  template:
    metadata:
      labels:
        name: {{ include "shipa.fullname" . }}-etcd
    spec:
      containers:
        - name: etcd
          image: "quay.io/coreos/etcd:v3.3.17"
          command: ['/usr/local/bin/etcd',
                    '--debug',
                    '--listen-client-urls', 'http://0.0.0.0:2379',
                    '--data-dir=/var/etcd/data',
                    '--advertise-client-urls', 'http://0.0.0.0:2379']
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 2379
              protocol: TCP
          env:
            - name: ETCDCTL_API
              value: "3"
          volumeMounts:
            - name: data
              mountPath: /var/etcd/data
              subPath: etcd
      volumes:
        - name: data
          {{- if .Values.etcd.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ template "shipa.fullname" . }}-etcd-pvc
          {{- else }}
          emptyDir: {}
          {{- end -}}
