apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "shipa.fullname" . }}-grafana
  labels: {{- include "shipa.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ template "shipa.fullname" . }}-grafana
  template:
    metadata:
      labels:
        name: {{ template "shipa.fullname" . }}-grafana
    spec:
      containers:
      - name: grafana
        image: {{ .Values.grafana.image }}
        imagePullPolicy: {{ .Values.grafana.pullPolicy }}
        ports:
        - name: grafana
          containerPort: 3000
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: storage
          - mountPath: /etc/grafana/provisioning/datasources/prometheus.yaml
            name: config
            subPath: prometheus.yaml
        env:
          - name: GF_SECURITY_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "shipa.fullname" . }}-secret
                key: grafana-password
          - name: GF_SECURITY_ADMIN_USER
            value: admin
          - name: GF_SERVER_SERVE_FROM_SUB_PATH
            value: "true"
          - name: GF_SERVER_ROOT_URL
            value: /grafana/
          - name: METRICS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "shipa.fullname" . }}-secret
                key: metrics-password
      volumes:
        - name: storage
          emptyDir: {}
        - name: config
          configMap:
              defaultMode: 420
              name: {{ template "shipa.fullname" . }}-grafana-config
