{{- if .Values.guardian.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "shipa.fullname" . }}-guardian-pvc
  labels:
    app: {{ template "shipa.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ .Values.guardian.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.guardian.persistence.size | quote }}
{{- if .Values.guardian.persistence.storageClass }}
{{- if (eq "-" .Values.guardian.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.guardian.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
