apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shipa.fullname" . }}-guardian
  labels: {{- include "shipa.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ include "shipa.fullname" . }}-guardian
  template:
    metadata:
      labels:
        name: {{ include "shipa.fullname" . }}-guardian
    spec:
      terminationGracePeriodSeconds: 3
      containers:
        - name: guardian
          image: {{ .Values.guardian.image }}
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 8000
              protocol: TCP
            - name: ssh
              containerPort: 22
              protocol: TCP
          env:
            - name: MONGODB_ADDR
              value: {{ include "shipa.fullname" . }}-mongodb-replicaset
            - name: MONGODB_PORT
              value: "27017"
            - name: SHIPA_HOST
              value: "http://{{ include "shipa.fullname" . }}-api.{{ .Release.Namespace }}:{{ .Values.shipaApi.port }}"
            - name: SHIPA_USER
              value: {{ required "Admin username required" .Values.auth.adminUser }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/guardian
            - name: home-git
              mountPath: /home/git
            - name: credentials
              mountPath: /etc/shipa
      volumes:
        - name: credentials
          secret:
            secretName: shipa-guardian
        - name: home-git
          emptyDir: {}
        - name: data
          {{- if .Values.guardian.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ template "shipa.fullname" . }}-guardian-pvc
          {{- else }}
          emptyDir: {}
          {{- end -}}
