apiVersion: v1
kind: Service
metadata:
  name: {{ template "shipa.fullname" . }}-guardian
  labels: {{- include "shipa.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    name: {{ template "shipa.fullname" . }}-guardian
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: web
    - port: {{ .Values.guardian.sshPort }}
      targetPort: 22
      protocol: TCP
      name: ssh
