apiVersion: v1
kind: Service
metadata:
  name: {{ include "shipa.fullname" . }}-guardian
  labels:
    name: guardian
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: web
    - port: 22
      targetPort: 22
      protocol: TCP
      name: ssh
  selector:
    name: guardian
