apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "shipa.fullname" . }}-guardian
  labels: {{- include "shipa.labels" . | nindent 4 }}
  annotations:
    "sidecar.istio.io/inject: "false"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ template "shipa.fullname" . }}-guardian
  template:
    metadata:
      labels:
        name: {{ template "shipa.fullname" . }}-guardian
    spec:
      terminationGracePeriodSeconds: 3
      containers:
        - name: guardian
          image: {{ .Values.guardian.image }}
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 8000
              protocol: TCP
            - name: ssh
              containerPort: 22
              protocol: TCP
          env:
            - name: MONGODB_ADDR
              value: {{ .Release.Name }}-mongodb-replicaset
            - name: MONGODB_PORT
              value: "27017"
            - name: SHIPA_HOST
              value: "http://{{ template "shipa.fullname" . }}-api.{{ .Release.Namespace }}:{{ .Values.shipaApi.port }}"
            - name: SHIPA_USER
              value: {{ required "Admin username required" .Values.auth.adminUser }}
          volumeMounts:
            - name: repositories-data
              mountPath: /var/lib/guardian
              subPath: guardian
            - name: home-git-data
              mountPath: /home/git
              subPath: home
            - name: credentials
              mountPath: /etc/shipa
      volumes:
        - name: credentials
          secret:
            secretName: shipa-guardian
        - name: home-git-data
          persistentVolumeClaim:
            claimName: {{ template "shipa.fullname" . }}-guardian-home-git-pvc
        - name: repositories-data
          persistentVolumeClaim:
            claimName: {{ template "shipa.fullname" . }}-guardian-repositories-pvc
