apiVersion: v1
kind: Secret
metadata:
  name: shipa-guardian
  labels:
    app: {{ template "shipa.name" . }}
    chart: {{ template "shipa.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  token: ""
