apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "shipa.fullname" . }}-metrics-config
  labels: {{- include "shipa.labels" . | nindent 4 }}
data:
  prometheus.yml: |-
    global:
      scrape_interval: 1m

    scrape_configs:
      - job_name: "pushgateway"
        honor_labels: true
        scheme: http
        static_configs:
          - targets: ['127.0.0.1:9093']
            labels:
              source: pushgateway

      - job_name: "traefik"
        honor_labels: true
        scheme: http
        static_configs:
          - targets: ['{{ template "shipa.fullname" . }}-traefik-internal.{{ .Release.Namespace }}:9095']
