apiVersion: v1
kind: Service
metadata:
  name: {{ include "shipa.fullname" . }}-metrics
  labels:
    name: {{ include "shipa.fullname" . }}-metrics
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: prometheus
    - port: 9091
      targetPort: 9091
      protocol: TCP
      name: pushgateway
  selector:
    name: {{ include "shipa.fullname" . }}-metrics
