apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "shipa.fullname" . }}-metrics
  labels: {{- include "shipa.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      name: {{ template "shipa.fullname" . }}-metrics
  template:
    metadata:
      labels:
        name: {{ template "shipa.fullname" . }}-metrics
    spec:
      containers:
        # Please do not scale metrics container. It doesn't use storage lock (--storage.tsdb.no-lockfile)
        - name: metrics
          image: {{ .Values.metrics.image }}
          imagePullPolicy: {{ .Values.metrics.pullPolicy }}
          env:
            - name: METRICS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "shipa.fullname" . }}-secret
                  key: metrics-password
          ports:
            - name: prometheus
              containerPort: 9090
              protocol: TCP
            - name: pushgateway
              containerPort: 9091
              protocol: TCP
          volumeMounts:
            - name: "{{ template "shipa.fullname" . }}-metrics-config"
              mountPath: /etc/prometheus/config
      volumes:
        - name: {{ template "shipa.fullname" . }}-metrics-config
          configMap:
            name: {{ template "shipa.fullname" . }}-metrics-config
            items:
                - key: prometheus.yml
                  path: prometheus.yml
