kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "shipa.fullname" . }}-metrics-pvc
  labels: {{- include "shipa.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.metrics.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.metrics.persistence.size | quote }}
  {{- if .Values.metrics.persistence.storageClass }}
  {{- if (eq "-" .Values.metrics.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.metrics.persistence.storageClass }}"
  {{- end }}
  {{- end }}
