apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "shipa.fullname" . }}-nginx-ingress-serviceaccount
  labels:
    app.kubernetes.io/name: {{ template "shipa.fullname" . }}-ingress-nginx
    app.kubernetes.io/part-of: {{ template "shipa.fullname" . }}-ingress-nginx
