apiVersion: v1
kind: Service
metadata:
  name: {{ template "shipa.fullname" . }}-ingress-nginx
  labels: {{- include "shipa.labels" . | nindent 4 }}
spec:
  type: "{{ .Values.service.nginx.serviceType }}"
  {{- if .Values.service.nginx.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.service.nginx.loadBalancerIP }}"
  {{- end }}
  {{- if .Values.service.nginx.clusterIP }}
  clusterIP: "{{ .Values.service.nginx.clusterIP }}"
  {{- end }}
  selector:
    name: {{ template "shipa.fullname" . }}-nginx-ingress
  ports:
    - port: {{ .Values.guardian.sshPort }}
      name: guardian
      targetPort: {{ .Values.guardian.sshPort }}
      protocol: TCP
    - port: {{ ( index .Values "docker-registry").service.port }}
      name: registry
      targetPort: {{ ( index .Values "docker-registry").service.port }}
      protocol: TCP
    - port: {{ .Values.shipaApi.securePort }}
      name: shipa-secure
      targetPort: {{ .Values.shipaApi.securePort }}
      protocol: TCP
    - port:  {{ .Values.shipaApi.port }}
      name: shipa
      targetPort: {{ .Values.shipaApi.port }}
      protocol: TCP
    - port: 2379
      name: etcd
      targetPort: 2379
      protocol: TCP
