apiVersion: v1
kind: Service
metadata:
  name: {{ template "shipa.fullname" . }}-ingress-nginx
  labels: {{- include "shipa.labels" . | nindent 4 }}
spec:
  type: "{{ .Values.service.nginx.serviceType }}"
  {{- if .Values.service.nginx.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.service.nginx.loadBalancerIP }}"
  {{- end }}
  {{- if .Values.service.nginx.clusterIP }}
  clusterIP: "{{ .Values.service.nginx.clusterIP }}"
  {{- end }}
  selector:
    name: {{ template "shipa.fullname" . }}-nginx-ingress
  ports:
    - port: 22
      name: guardian
      targetPort: 22
      protocol: TCP
    - port: 5000
      name: registry
      targetPort: 5000
      protocol: TCP
    - port: 8080
      name: shipa
      targetPort: 8080
      protocol: TCP
    - port: 9090
      name: prometheus
      targetPort: 9090
      protocol: TCP
    - port: 9091
      name: pushgateway
      targetPort: 9091
      protocol: TCP
