apiVersion: v1
kind: Service
metadata:
  name: {{ include "shipa.fullname" . }}-postgres
  labels: {{- include "shipa.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    name: {{ include "shipa.fullname" . }}-postgres
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
