apiVersion: v1
kind: Service
metadata:
  name: {{ include "shipa.fullname" . }}-postgres
  labels:
    name: {{ include "shipa.fullname" . }}-postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    name: {{ include "shipa.fullname" . }}-postgres
