apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "shipa.fullname" . }}-postgres
  labels: {{- include "shipa.labels" . | nindent 4 }}
  annotations:
    "sidecar.istio.io/inject: "false"
spec:
  selector:
    matchLabels:
      name: {{ template "shipa.fullname" . }}-postgres
  template:
    metadata:
      labels:
        name: {{ template "shipa.fullname" . }}-postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          imagePullPolicy: IfNotPresent
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "shipa.fullname" . }}-secret
                  key: postgres-password
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ template "shipa.fullname" . }}-postgres-pvc
