apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-init-job-{{ .Release.Revision }}"
  labels: {{- include "shipa.labels" . | nindent 4 }}
spec:
  backoffLimit: 5
  template:
    metadata:
      name: "{{ .Release.Name }}-init-job-{{ .Release.Revision }}"
      labels:
        app: {{ template "shipa.name" . }}
        chart: {{ template "shipa.chart" . }}
    spec:
      terminationGracePeriodSeconds: 3
      {{- if .Values.rbac.enabled }}
      serviceAccountName: {{ template "shipa.fullname" . }}
      {{- else }}
      serviceAccountName: default
      {{- end }}
      restartPolicy: Never
      containers:
        - name: migrations
          image: {{ .Values.cli.image }}
          command:
            - /init/init-job.sh
          imagePullPolicy: {{ .Values.cli.pullPolicy }}
          env:
            - name: SHIPA_ENDPOINT
              value: "{{ .Release.Name }}-api:{{ .Values.service.port }}"
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-api-init-secret
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-api-init-secret
                  key: password
            - name: TRAEFIK_SERVICE
              value: {{ template "shipa.fullname" . }}-traefik
            - name: NGINX_SERVICE
              value: {{ template "shipa.fullname" . }}-ingress-nginx
            - name: TRAEFIK_SERVICE_TYPE
              value: {{ .Values.service.traefik.serviceType }}
            - name: NGINX_SERVICE_TYPE
              value: {{ .Values.service.nginx.serviceType }}
            - name: DASHBOARD_IMAGE
              value: {{ .Values.dashboard.image }}
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: init
              mountPath: /init
      volumes:
        - name: init
          configMap:
            defaultMode: 0755
            name: {{ template "shipa.fullname" . }}-api-init-config
