apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "shipa.fullname" . }}-api-init-config
  labels: {{- include "shipa.labels" . | nindent 4 }}
data:
  common.sh: |
{{ .Files.Get "scripts/common.sh" | indent 4 }}
  create-root-user.sh: |
{{ .Files.Get "scripts/create-root-user.sh" | indent 4 }}
  init-job.sh: |
{{ .Files.Get "scripts/init-job.sh" | indent 4 }}
  bootstrap.sh: |
{{ .Files.Get "scripts/bootstrap.sh" | indent 4 }}
  csr-docker-cluster.json: |
{{ .Files.Get "scripts/csr-docker-cluster.json" | indent 4 }}
  csr-docker-registry.json: |
{{ .Files.Get "scripts/csr-docker-registry.json" | indent 4 }}
  csr-shipa-ca.json: |
{{ .Files.Get "scripts/csr-shipa-ca.json" | indent 4 }}
