{{- if .Values.externalMongodb.enable }}
{{- if .Values.externalMongodb.auth.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "shipa.fullname" . }}-db-auth-secret
  labels: {{- include "shipa.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  username: {{ required "Database username is required! Use --set=externalMongodb.auth.username=..." .Values.externalMongodb.auth.username | b64enc }}
  password: {{ required "Database password is required! Use --set=externalMongodb.auth.password=..." .Values.externalMongodb.auth.password | b64enc }}
{{- end }}
{{- end }}