apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "shipa.fullname" . }}-api-config
  labels: {{- include "shipa.labels" . | nindent 4 }}
data:
  shipa.conf: |-
    listen: "0.0.0.0:{{ .Values.shipaApi.port }}"
    host: http://SHIPA_PUBLIC_IP:{{ .Values.shipaApi.port }}
    use-tls: false
    repo-manager: guardian
    database:
      url: {{ .Release.Name }}-mongodb-replicaset:27017
      name: shipa
    auth:
      token-expire-days: 2
      hash-cost: 4
      user-registration: true
    provisioner: kubernetes
    platforms:
      build-pool: theonepool
    metrics:
      host: {{ template "shipa.fullname" . }}-metrics
      password: $METRICS_PASSWORD
    docker:
      bb:
        socket: /var/run/docker.sock
      cluster:
        storage: mongodb
        mongo-url: {{ .Release.Name }}-mongodb-replicaset:27017
        mongo-database: cluster
      collection: docker
      registry: SHIPA_PUBLIC_IP:{{ ( index .Values "docker-registry" ).service.port }}
      registry-scheme: https
      registry-auth:
        username: admin
        password: $DOCKER_REGISTRY_PASSWORD
      registry-token-signer:
        key-file: /certs/ca-key.pem
        cert-file: /certs/ca.pem
      repository-namespace: shipa
      router: traefik
      deploy-cmd: /var/lib/shipa/deploy
      run-cmd:
        bin: /var/lib/shipa/start
        port: "8888"
      tls:
        root-path: /certs
      auto-scale:
        enabled: true
        run-interval: $DOCKER_AUTOSCALE_RUN_INTERVAL
    routers:
      traefik:
        type: traefik
        domain: TRAEFIK_IP.nip.io
        kv:
          prefix: traefik
          store-type: etcdv3
          endpoint: {{ template "shipa.fullname" . }}-etcd:2379
    queue:
      mongo-url: {{ .Release.Name }}-mongodb-replicaset:27017
      mongo-database: queuedb
    quota:
      units-per-app: 4
      apps-per-user: 8
    log:
      disable-syslog: true
      use-stderr: true
    git:
      api-server: http://{{ template "shipa.fullname" . }}-guardian:8000
    clair:
      server: http://{{ template "shipa.fullname" . }}-clair:6060
      disable: false
    kubernetes:
      use-pool-namespaces: false
    debug: true
