{{- if .Values.rbac.enabled }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ template "shipa.fullname" . }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "shipa.fullname" . }}
rules:
  - apiGroups:
      - ""
      - extensions
      - rbac.authorization.k8s.io
      - apiextensions.k8s.io
      - core
      - apps
      - shipa.io
    resources: ["*"]
    verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "shipa.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "shipa.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "shipa.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
