apiVersion: v1
kind: Service
metadata:
  name: {{ include "shipa.fullname" . }}-api
  labels:
    {{- include "shipa.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "shipa.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: shipa
