apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "shipa.fullname" . }}-traefik-config
  labels: {{- include "shipa.labels" . | nindent 4 }}
data:
  traefik.toml: |-
    defaultEntryPoints = ["http"]
    accessLogsFile = "/dev/stdout"
    debug = {{ .Values.service.traefik.debug }}
    [metrics]
      [metrics.prometheus]
        entryPoint = "traefik"
        buckets = [0.005, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1,0.3,0.7,1.0,1.5,2.0,2.5,3.0,3.5,4.0,4.5,5.0]

    [entryPoints]
      [entryPoints.http]
      address = ":{{ .Values.service.traefik.httpPort }}"
      [entryPoints.https]
      address = ":{{ .Values.service.traefik.httpsPort }}"
        [entryPoints.https.tls]

      [entryPoints.traefik]
      address = ":9095"

    [acme]
    email = "{{ .Values.auth.adminUser }}"
    storage = "acme/account/tls"
    onHostRule = true
    entryPoint = "https"
      [acme.httpChallenge]
      entryPoint = "http"

    [api]
    entryPoint = "traefik"
    dashboard = true

    [etcd]
    endpoint = "{{ template "shipa.fullname" . }}-etcd:2379"
    watch = true
    prefix = "/traefik"
    useAPIv3 = true
    username = "root"
      [etcd.tls]
      ca = "/etc/shipa/ssl/shipa-ca.crt"
      cert = "/etc/shipa/ssl/etcd-client.crt"
      key = "/etc/shipa/ssl/etcd-client.key"
      insecureSkipVerify = false

    [kubernetes]
    ingressClass = "shipa-traefik-core"
